### ISSUE TITLE
usb command needs to install u-root gpt cmd

### ISSUE THREAD

**Issue by thienhoang23** [u-root/NiChrome#58]
commit id: b5722be233daf03340b161e5efb3d9d4c3c265f1

1. Ran usb command.
2. Got error because the gpt command is not installed on the machine.  

```
2018/01/30 16:23:46 gpt [/[GOPATH]/bin/gpt /dev/sda] failed (warning only): exit status 1
Bz image is located at linux-stable/arch/x86/boot/bzImage
```

**Comment by hugelgupf** [comment]
It shouldn't install the command. It should depend on the code that gpt is implemented with as a package rather than running gpt as a subprocess.

**Comment by rminnich** [comment]
it has to run it as a process, sadly. I don't want the usb command running as root, but to read a gpt, you need a process to run as root. The easiest way to do this is run gpt via sudo. 

I did use the gpt package in an earlier version but took it out when I realized we don't want the entire usb command running as root. Root activities need to be bounded in time.
