### ISSUE TITLE
usb command did not build the correct usb stick, resulting in a boot failing to start user terminal and Chrome browser

### ISSUE THREAD

**Issue by thienhoang23** [u-root/NiChrome#60]
Commit id: b5722be233daf03340b161e5efb3d9d4c3c265f1

Steps for reproduction:
1. Plug in the usb stick into build machine and find out what device it is (in this case, it was /dev/sda)
2. From the project root directory, go to the usb subdirectory and build the usb command in this directory
```
$ cd usb && go build .
```
3. Install the u-root's command gpt. Change back to the root directory. Run the usb command. 
```
$ go install github.com/u-root/u-root/cmds/gpt
$ cd ..
$ ./usb/usb -fetch=true -dev=/the/name/of/device
```
4. Unplug the usb stick from build machine and plug it into a Chromebook
5. Turn on a Chromebook. When the dev-mode screen appears, press `Ctrl-U`
6. After boot, observe that Chrome browser and user terminal do not start.
7. `Ctrl-Alt-backspace` to exit X11
8. Notice the following error message about tempfs mount on /pkg failing:
`Error creating mount -t "tmpfs" -o "temps" "/pkg" flags 0x0: no such file or directory: not starting user x11 programs`

Further examination showed that there was no /pkg directory

**Comment by rminnich** [comment]
Turns out this is fixed by a commit I had hanging, but trying to push that revealed lots of other problems ... should be fixed tomorrow.

**Comment by rminnich** [comment]
This is now fixed.
