### ISSUE TITLE
NiChrome was not updated alongside u-root

### ISSUE THREAD

**Issue by jbeta51** [u-root/NiChrome#90]
> cmds/install/install.go:63:13: assignment mismatch: 3 variables but 2 values
> cmds/install/install.go:111:12: assignment mismatch: 3 variables but 2 values
> github.com/u-root/u-root/bb/cmds/uinit
cmds/uinit/uinit.go:101:13: assignment mismatch: 3 variables but 2 values
exit status 2
exit status 1
2018/06/04 10:21:53 fail error is : Build static initramfs: exit status 1
----------------------------------
> cmds/install/install.go:70:7: g.Parts undefined (type *gpt.PartitionTable has no field or method Parts)
> cmds/install/install.go:72:34: g.Parts undefined (type *gpt.PartitionTable has no field or method Parts)
> cmds/install/install.go:152:3: g.Parts undefined (type *gpt.PartitionTable has no field or method Parts)
exit status 2
exit status 1
2018/06/04 10:34:06 fail error is : Build static initramfs: exit status 1
----------------------------------
Argument mismatch and other usage errors where NiChrome install.go and uinit.go files use GPT. Need to modify NiChrome to reflect changes made in u-root.

**Comment by hugelgupf** [comment]
This is why you vendor - you should talk about it with Gan and me when we're back later
